name = "omni-repository"
[server]
publicHttpPort = 8080
internalHttpPort = 8088
dataFolder = "./data/"
[log]
logFile = "/app/logs/run-application-{date}.log"
errFile = "/app/logs/run-error-{date}.log"
[repoManager]
[workManager]
threads = 10
syncInterval = 30
    [workManager.workers.imagerPusher]
        endpoint = "obs.ap-southeast-1.myhuaweicloud.com"
        ak = ""
        sk = ""
        bucket = ""
        partSize = 419430400
[persistentStore]
host = "192.168.1.193"
user = "root"
password = "rootpswd"
dbname = "omni_repository"
port = "3306"
[mq]
kafka_brokers = "192.168.1.193:9092"