name = "omni-repository"
timezone = "PRC"
httpPort = 8080
[log]
logFile = "/app/logs/run-application-{date}.log"
errFile = "/app/logs/run-error-{date}.log"
[repoManager]
dataFolder = "./data/"
uploadToken = "316462d0c029ba707ad1"
callBackUrl = "http://mymanager:8080/api/v3/baseImages/repoCallback/%d?status=%s"

[persistentStore]
host = "192.168.1.193"
user = "root"
password = "rootpswd"
dbname = "omni_repository"
port = "3306"