definitions:
  dtos.ImageRequest:
    properties:
      algorithm:
        enum:
        - md5
        - sha256
        type: string
      checksum:
        type: string
      desc:
        type: string
      externalComponent:
        type: string
      externalID:
        type: string
      fileName:
        type: string
      name:
        type: string
      publish:
        type: boolean
      sourceUrl:
        type: string
      userID:
        type: integer
    required:
    - algorithm
    - externalComponent
    - externalID
    - fileName
    - name
    - userID
    type: object
  models.Image:
    properties:
      algorithm:
        type: string
      checksum:
        type: string
      checksumPath:
        type: string
      createTime:
        type: string
      deleted:
        type: boolean
      desc:
        type: string
      externalComponent:
        type: string
      externalID:
        type: string
      fileName:
        type: string
      id:
        type: integer
      imagePath:
        type: string
      name:
        type: string
      publish:
        type: boolean
      sourceUrl:
        type: string
      status:
        type: string
      statusDetail:
        type: string
      updateTime:
        type: string
      userId:
        type: integer
    type: object
info:
  contact: {}
paths:
  /delete:
    post:
      consumes:
      - application/json
      description: deletes an image by user ID and checksum
      parameters:
      - description: userID
        in: query
        name: userID
        required: true
        type: string
      - description: checksum
        in: query
        name: checksum
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Image'
      summary: delete an image by user ID and checksum
      tags:
      - Image
  /load:
    post:
      consumes:
      - application/json
      description: create a image with specified parameter, image will be downloaded
        via source url
      parameters:
      - description: body for upload a image
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dtos.ImageRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Image'
      summary: create a image from external system
      tags:
      - Image
  /query:
    post:
      consumes:
      - application/json
      description: Upload a image with specified parameter
      parameters:
      - description: externalID
        in: query
        name: externalID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Image'
      summary: query image by external ID
      tags:
      - Image
  /upload:
    post:
      consumes:
      - application/json
      description: Upload a image with specified parameter
      parameters:
      - description: body for upload a image
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dtos.ImageRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Image'
      summary: upload a image
      tags:
      - Image
swagger: "2.0"
